### ISSUE TITLE
JVM Crash when using a specific jar : cloudera HS2Driver (Hive), any versions

### ISSUE THREAD

**Issue by TheCodingLand** [jpype-project/jpype#1137]
I try to use the cloudera Hive driver with Jpype, but the the JVM encouters  a fatal error.

here is some code to reproduce the error.

```python
from jpype import startJVM, shutdownJVM 
import jpype.imports
from jpype.types import * # pyright: ignore
from pathlib import Path
driver ="com.cloudera.hive.jdbc.HS2Driver"
jdbc_url= "jdbc:hive2://test.com:443/db" # any valid dns url

JVM_PATH = "jdk-20.0.1\\bin\\server\\jvm.dll"

hive_jar = Path(__file__).parent/ 'jar' / 'HiveJDBC42.jar'

startJVM(JVM_PATH, classpath=[str(hive_jar)])

from java.sql import DriverManager

conn_db = DriverManager.getConnection(jdbc_url, "username", "password")
conn_db.close()
```

The jar file itself can be obtained [here](https://www.cloudera.com/downloads/connectors/hive/jdbc/2-6-21.html)

Tested with many versions and different JDK versions as well.

You don't need an Hive environment to reproduce.

conda env used:

```yaml
name: jvm_test_jpype
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - jaydebeapi=1.2.3
  - jpype1=1.4.1
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.42.0
  - libzlib=1.2.13
  - openssl=3.1.1
  - packaging=23.1
  - pip=23.1.2
  - python=3.11.4
  - python_abi=3.11
  - setuptools=67.7.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.40.0
  

```

hs_err:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ff94901051c, pid=26732, tid=13640
#
# JRE version: Java(TM) SE Runtime Environment (20.0.1+9) (build 20.0.1+9-29)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (20.0.1+9-29, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [KERNELBASE.dll+0x9051c]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: 

Host: 13th Gen Intel(R) Core(TM) i9-13900KF, 32 cores, 63G,  Windows 11 , 64 bit Build 22621 (10.0.22621.1194)
Time: Thu Jun 15 15:28:10 2023 Paris, Madrid (heure d��t�) elapsed time: 21.452113 seconds (0d 0h 0m 21s)

---------------  T H R E A D  ---------------

Current thread (0x00000261c53737e0):  JavaThread "main" [_thread_in_native, id=13640, stack(0x000000917f600000,0x000000917f7f0000)]

Stack: [0x000000917f600000,0x000000917f7f0000],  sp=0x000000917f7dfb00,  free space=1918k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [KERNELBASE.dll+0x9051c]
C  [VCRUNTIME140.dll+0x6720]
C  [_jpype.cp311-win_amd64.pyd+0x3bca7]
C  [_jpype.cp311-win_amd64.pyd+0x2affb]
C  0x00000261d6361ff3

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.jpype.manager.TypeFactoryNative.newWrapper(JJ)V+0
j  org.jpype.JPypeContext.newWrapper(J)V+16
v  ~StubRoutines::call_stub 0x00000261d634100d

siginfo: EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363), ExceptionInformation=0x0000000019930520 0x000000917f7dfce0 0x00007ff842616d78 0x00007ff8425b0000 ...

```
